version: '3.3'
services:
  postgis:
    image: pgrouting/pgrouting:16-3.5
    container_name: postgis
    hostname: postgis
    environment:
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: postgis
      POSTGRES_DB: gis
    ports:
      - "55432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    networks:
      - big-data
volumes:
  postgis_data:
    external: true
    name: postgis_data

networks:
  big-data:
    external: true
