version: "3.3"

services:
  cassandra1:
    image: cassandra:3.11.19
    container_name: cassandra1
    hostname: cassandra1
    restart: unless-stopped
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_CLUSTER_NAME=c3-3.11.19-cluster
    volumes:
      - cassandra1_data:/var/lib/cassandra

  cassandra2:
    image: cassandra:3.11.19
    container_name: cassandra2
    hostname: cassandra2
    restart: unless-stopped
    depends_on:
      - cassandra1
    environment:
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_CLUSTER_NAME=c3-3.11.19-cluster
    volumes:
      - cassandra2_data:/var/lib/cassandra

  #cassandra3:
  #  image: cassandra:3.11.19
  #  container_name: cassandra3
  #  hostname: cassandra3
  #  restart: unless-stopped
  #  depends_on:
  #    - cassandra1
  #  environment:
  #    - CASSANDRA_SEEDS=cassandra1
  #    - CASSANDRA_CLUSTER_NAME=c3-3.11.19-cluster
  #  volumes:
  #    - cassandra3_data:/var/lib/cassandra

volumes:
  cassandra1_data:
    name: cassandra1_data
  cassandra2_data:
    name: cassandra2_data
  #cassandra3_data:
  #  name: cassandra3_data
